name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Enable corepack (pnpm)
        run: corepack enable
      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false

      - name: Typecheck
        run: pnpm typecheck
      - name: Lint
        run: pnpm lint
      - name: Format check
        run: pnpm format:check
      - name: Spellcheck
        run: pnpm cspell
      - name: Build
        run: pnpm build
      - name: HTML validate
        run: pnpm html:validate

      - name: Serve site
        run: pnpm ci:serve &
      - name: Wait for server
        run: npx wait-on http://127.0.0.1:4321

      - name: Link check
        run: npx linkinator http://127.0.0.1:4321 --recurse --timeout 30000

      - name: Axe accessibility scan
        run: npx @axe-core/cli http://127.0.0.1:4321 --threshold serious --exit --dir ./axe-report

      - name: Lighthouse
        run: npx lighthouse http://127.0.0.1:4321 --preset=desktop --output=json --output-path=./lhr.json && node -e "const r=require('./lhr.json'); const perf=(r.categories.performance.score||0); const acc=(r.categories.accessibility.score||0); if(perf<0.95){console.error('Perf score < 0.95'); process.exit(1);} if(acc<1){console.error('Accessibility score < 1.00'); process.exit(1);}"

      - name: Playwright smoke
        run: pnpm test
